print(list(range(10))) # range(0,10,1)
print("Lista de numeros com passo 1 no intervalo [0 ate 9]")
print("=============================")
print(list(range(2, 6)))
print("Lista de numeros com passo 1 no intervalo [2 ate 5]")
print("=============================")
print(list(range(0, 11, 1)))
print("Lista de numeros com passo 1 no intervalo [0 ate 10]")
print("=============================")
print(list(range(0, 21, 2)))
print("Lista de numeros com passo 2 no intervalo [0 ate 20]")
print("=============================")
print("Lista de numeros com passo 10  no intervalo [0 ate 100]")
print(list(range(0, 100, 10))) # Incrementador em 10(step)
print("=============================")
print("Lista de numeros com passo -10 impares no intervalo [100 ate 10]")
print(list(range(100, 0, -10)))  # Decrementador em -10(step)

for cont in range(10, 0, -1):
    print(cont)